---
- name: Check ping connectivity
  ansible.builtin.ping:

- name: Check SSH port 22
  ansible.builtin.wait_for:
    port: 22
    timeout: 5
    state: started

- name: Read OS release file
  ansible.builtin.command: cat /etc/os-release
    register: os_info
    changed_when: false

- name: Display OS release info
  ansible.builtin.debug:
    msg: "{{ os_info.stdout_lines }}"

